<a href="https://colab.research.google.com/github/arman-hossain45/DL_Community/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BAsic pytorch implementation with details


In [1]:
import torch

When we do code in pytorch we must define this tensor for  implementation . or convert it to tensor for more details

In [3]:
# input
x = torch.tensor([2.0])

# weight and bias implementation
w = torch.tensor([0.5],requires_grad=True)
b = torch.tensor([1.0],requires_grad=True)

# neuron output

y=w*x+b

print("Input :",x)
print('weights :',w)
print("Bias", b)
print("Output", y)

Input : tensor([2.])
weights : tensor([0.5000], requires_grad=True)
Bias tensor([1.], requires_grad=True)
Output tensor([2.], grad_fn=<AddBackward0>)


*Manually define weights and bias using this pytorch tensor in details*

In [4]:
x = torch.tensor([1.0,2.0])

w = torch.tensor (
    [
        [0.1,0.2],
        [0.3,0.4],
        [0.5,0.6]

    ]
)

b = torch.tensor ([0.1,0.2,0.3])

output = torch.matmul(w,x) + b

print(output)

tensor([0.6000, 1.3000, 2.0000])


# Basic neural network

In [7]:
import torch.nn as nn

layer= nn.Linear(2,3)# here totall input is 2 and output neuron is 3 so for that reason totall weights is 6 and totall bias is 3

print(layer.weight)
print(layer.bias)

Parameter containing:
tensor([[ 0.5054, -0.0894],
        [-0.5531,  0.1570],
        [ 0.0157,  0.3836]], requires_grad=True)
Parameter containing:
tensor([-0.1805,  0.2239,  0.3283], requires_grad=True)


# Bassic neural  network formation

Single layer

In [11]:
layer  = nn.Linear(2,3)

x = torch.tensor([1.0,2.0])

output = layer(x)

print ('Input')
print(x)

print('Weights',layer.weight)
print('Bias',layer.bias)
print("outputs :",output)

Input
tensor([1., 2.])
Weights Parameter containing:
tensor([[-0.4453,  0.2472],
        [ 0.4082,  0.4679],
        [-0.2196, -0.2455]], requires_grad=True)
Bias Parameter containing:
tensor([-0.4418,  0.5896,  0.3649], requires_grad=True)
outputs : tensor([-0.3928,  1.9335, -0.3458], grad_fn=<ViewBackward0>)


# 2 layer  neural network formation in details

In [13]:
layer1= nn.Linear(2,3)
layer2= nn.Linear(3,1)

# INPUTS
x=torch.tensor([1.0,2.0])

h=layer1(x)

y=layer2(h)

print("Inputs",x)

print('\n layer 1 outputs \n',h)
print('\n layeer 2 outputs \n',y)

Inputs tensor([1., 2.])

 layer 1 outputs 
 tensor([-0.3722,  0.2848, -0.5478], grad_fn=<ViewBackward0>)

 layeer 2 outputs 
 tensor([-0.4545], grad_fn=<ViewBackward0>)


In [15]:
print("Layer1 Weights")
print(layer1.weight)

print("Layer1 Bias")
print(layer1.bias)

print("Layer1 Output")
print(h)

print("----------------")

print("Layer2 Weights")
print(layer2.weight)

print("Layer2 Bias")
print(layer2.bias)

print("Final Output")
print(y)

Layer1 Weights
Parameter containing:
tensor([[ 0.0869, -0.2678],
        [-0.2232, -0.0303],
        [ 0.6476, -0.2605]], requires_grad=True)
Layer1 Bias
Parameter containing:
tensor([ 0.0765,  0.5687, -0.6745], requires_grad=True)
Layer1 Output
tensor([-0.3722,  0.2848, -0.5478], grad_fn=<ViewBackward0>)
----------------
Layer2 Weights
Parameter containing:
tensor([[ 0.4729, -0.2993, -0.2114]], requires_grad=True)
Layer2 Bias
Parameter containing:
tensor([-0.3091], requires_grad=True)
Final Output
tensor([-0.4545], grad_fn=<ViewBackward0>)


#looss calculation in this outputs we see that only one outputs and now we calculate  the overall loss off this

In [17]:
target = torch.tensor([10.0])

loss = (y-target)**2

print(loss)

tensor([109.2974], grad_fn=<PowBackward0>)


In [18]:
# compute this gradients
loss.backward()

In [19]:
print(layer1.weight.grad)
print(layer1.bias.grad)

print(layer2.weight.grad)
print(layer2.bias.grad)

tensor([[ -9.8879, -19.7758],
        [  6.2584,  12.5168],
        [  4.4209,   8.8418]])
tensor([-9.8879,  6.2584,  4.4209])
tensor([[ 7.7813, -5.9541, 11.4546]])
tensor([-20.9091])


# weights and bias upgrade formula in detials

In [22]:
lr = 0.01

with torch.no_grad():

    layer1.weight -= lr * layer1.weight.grad
    layer1.bias -= lr * layer1.bias.grad

    layer2.weight -= lr * layer2.weight.grad
    layer2.bias -= lr * layer2.bias.grad

In [21]:
layer1.weight.grad.zero_()
layer1.bias.grad.zero_()

layer2.weight.grad.zero_()
layer2.bias.grad.zero_()

tensor([0.])

**Full training process in pytorch**


In [23]:
import torch
import torch.nn as nn
x = torch.tensor([
    [1.0],
    [2.0],
    [3.0],
    [4.0]

])

y = torch.tensor([
    [2.0],
    [3.0],
    [5.0],
    [6.0]
])

In [24]:
model = nn.Linear(1,1)# here one input and one  outputs
criterion = nn.MSELoss()# define this loss function in details
optimizer = torch.optim.SGD(# optimizer define in this code
    model.parameters(),
    lr = 0.01
)

In [25]:
# Trainning  loop in details with code explanation

for epoch  in range(100):
  prediction =  model(x)
  loss = criterion(prediction,y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 10 == 0:
    print(epoch,loss.item())

0 2.7249934673309326
10 0.12126684933900833
20 0.05378234013915062
30 0.05192340910434723
40 0.05176915228366852
50 0.05166503041982651
60 0.051568061113357544
70 0.05147680640220642
80 0.051390912383794785
90 0.051309917122125626


In [26]:
# model weights and bias calculation in details

In [27]:
print("Weight")
print(model.weight)

print("Bias")
print(model.bias)

Weight
Parameter containing:
tensor([[1.3708]], requires_grad=True)
Bias
Parameter containing:
tensor([0.5859], requires_grad=True)


# sIMPLE PROJECT USING SIMPLE PYTORCH FORMULA IN DETAILS

In [28]:
import  torch
import  torch.nn as nn
import torch.optim as optim

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [29]:
housing = fetch_california_housing()

x = housing.data
y = housing.target

print("Features shape ", x.shape)
print("Target shape : ", y.shape)

Features shape  (20640, 8)
Target shape :  (20640,)


In [30]:
print(housing.feature_names)

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']


In [31]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)


In [32]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

so we code this  in pytorch for that reason we convert it in tensor

In [33]:
x_train = torch.tensor(x_train,dtype=torch.float32)
x_test = torch.tensor(x_test,dtype = torch.float32)
y_train = torch.tensor(y_train,dtype=torch.float32)
y_test = torch.tensor(y_test,dtype=torch.float32)

In [34]:
print(x_train.shape)
print(y_train.shape)

torch.Size([16512, 8])
torch.Size([16512])


In [35]:
# declaire the overall model in details
model = nn.Sequential(
    nn.Linear(8,64),
    nn.ReLU(),

    nn.Linear(64,32),
    nn.ReLU(),

    nn.Linear(32,1)
)

print(model)

Sequential(
  (0): Linear(in_features=8, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=1, bias=True)
)


In [37]:
# define this neural network using class
def __init__(self):
  super().__init__()
  self.network = nn.Sequential(
      nn.Linear(8,64),
      nn.ReLU(),

      nn.Linear(64,32),
      nn.ReLU(),

      nn.Linear(32,1)
  )

def forward(self,x):
  return self.network(x)

In [38]:
criterion = nn.MSELoss()
optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)

In [39]:
epochs =100

for epoch in range(epochs):
  model.train()
  prediction = model(x_train)
  loss = criterion(prediction,y_train)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 10 ==0:
    print(
        f"Epoch {epoch :3d}|"
        f"Loss : {loss.item():4f}"
    )

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([16512])) that is different to the input size (torch.Size([16512, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch   0|Loss : 5.415299
Epoch  10|Loss : 4.605777
Epoch  20|Loss : 3.711606
Epoch  30|Loss : 2.803738
Epoch  40|Loss : 2.090124
Epoch  50|Loss : 1.723012
Epoch  60|Loss : 1.593289
Epoch  70|Loss : 1.526589
Epoch  80|Loss : 1.498725
Epoch  90|Loss : 1.482038


In [40]:

model.eval()
with torch.no_grad():

    test_predictions = model(x_test)

    test_loss = criterion(
        test_predictions,
        y_test
    )

print("Test MSE:", test_loss.item())

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([4128])) that is different to the input size (torch.Size([4128, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Test MSE: 1.4402225017547607


In [41]:
rmse = torch.sqrt(test_loss)

print("RMSE:", rmse.item())

RMSE: 1.2000926733016968


In [42]:
from sklearn.metrics import r2_score

r2 = r2_score(
    y_test.numpy(),
    test_predictions.numpy()
)

print("R²:", r2)

R²: -0.1147918701171875
